package com.patricktinkam.firsteditioncompanion;

import java.util.*;

/** Native, paraphrased character-class reference for the PHB and supplied UA variant. */
public final class ClassData {
  public static final class Entry {
    public final String name, family, source, requirements, hitDie, alignment, armorWeapons, details;
    Entry(String name,String family,String source,String requirements,String hitDie,String alignment,String armorWeapons,String details){
      this.name=name; this.family=family; this.source=source; this.requirements=requirements;
      this.hitDie=hitDie; this.alignment=alignment; this.armorWeapons=armorWeapons; this.details=details;
    }
    public String label(){ return name+"  ["+source+"]"; }
    public String quick(){ return requirements+"  •  Hit Die: "+hitDie+"  •  Alignment: "+alignment; }
    public String fullDetails(){
      return "Class: "+name+"\nClass family: "+family+"\nSource: "+source+
        "\n\nRequirements / prime requisite: "+requirements+"\nHit Die: "+hitDie+
        "\nAlignment: "+alignment+"\nArmor & weapons: "+armorWeapons+"\n\n"+details;
    }
  }

  private static final ArrayList<Entry> ALL=new ArrayList<>();
  static {
    add("Cleric","Cleric","PHB","WIS 9 minimum; Wisdom is the principal attribute","d8","Any except true neutral","Any armor and shield; non-edged/non-pointed weapons such as club, flail, hammer, mace, and staff",
      "Clerics are armored divine spellcasters and competent melee combatants. They prepare divine spells through prayer, use holy symbols, and can turn undead; evil clerics use the corresponding control rules. High Wisdom can grant bonus spells, and Wisdom above 15 grants the PHB experience bonus.\n\nAt higher levels clerics can attract followers and establish a religious stronghold. Certain nonhuman races can multiclass as clerics. When cleric is combined with an eligible fighter-type, the PHB permits edged weapons for the combination.");

    add("Druid","Cleric subclass","PHB","WIS 12 minimum; CHA 15 minimum; both over 15 for the 10% XP bonus","d8","True neutral","Leather armor, wooden shield; club, dagger, dart, hammer, scimitar, sling, spear, staff",
      "Druids are true-neutral nature priests with their own divine spell list. They cannot turn undead and are restricted from metal armor. They receive a saving-throw benefit against fire and lightning and gain progressively stronger nature abilities.\n\nAt 3rd level they gain plant, animal, and pure-water identification and can move through natural undergrowth without leaving a normal trail. At 7th level they gain woodland charm immunity and limited animal shapechanging. High-level druid ranks are numerically limited, so advancement into the upper hierarchy can require defeating an incumbent.");

    add("Fighter","Fighter","PHB","STR 9 minimum; CON 7 minimum; Strength is the principal attribute","d10","Any","Any armor, shield, and weapon",
      "Fighters are the broadest PHB weapon-and-armor specialists. They use d10 hit dice, have the strongest conventional attack progression, and gain the fighter multiple-attack schedule as level increases. Strength above 15 grants the PHB experience bonus.\n\nAt 9th level a fighter can establish a freehold. If the surrounding territory is cleared and held, the fighter can attract men-at-arms and collect revenue. Paladin and ranger are fighter subclasses with additional restrictions and powers.");

    add("Paladin","Fighter subclass","PHB","Human; STR 12, INT 9, WIS 13, CON 9, CHA 17 minimum; STR and WIS both over 15 for 10% XP bonus","d10","Lawful good only","Any armor, shield, and weapon",
      "Paladins combine fighter combat ability with lawful-good divine powers. Core benefits include detect evil while concentrating, +2 on all saves, disease immunity, lay on hands once per day for 2 hit points per paladin level, cure disease, and a continuing protection-from-evil aura.\n\nAt 3rd level they gain a cleric-like ability against undead and certain fiends; at 4th they may call a special warhorse. Cleric spellcasting begins at 9th level. Paladins also have strict conduct, tithing, wealth, and magic-item limits. Knowingly committing an evil act permanently ends paladin status under the PHB rule.");

    add("Ranger","Fighter subclass","PHB","STR 13, INT 13, WIS 14, CON 14 minimum; STR, INT, and WIS all over 15 for 10% XP bonus","2d8 at 1st, then d8 progression","Any good","Fighter-style armor and weapons under ranger restrictions",
      "Rangers are good-aligned fighter subclasses specializing in tracking, woodcraft, scouting, and fighting the PHB's listed giant-class humanoids. They begin with 2d8 hit dice, have superior surprise chances, and add ranger level to melee damage against the designated giant-class enemies.\n\nTheir tracking rules cover both dungeons and wilderness, with modifiers for time, weather, doors, hidden routes, and party size. Limited druid spells begin at 8th level and magic-user spells at 9th; special followers arrive at 10th. Becoming non-good permanently removes ranger status and converts the character to fighter.");

    add("Magic-User","Magic-User","PHB","INT 9 minimum; DEX 6 minimum; Intelligence is the principal attribute; INT 16+ gives 10% XP bonus","d4","Any","No armor or shield; highly restricted weapons, chiefly dagger, dart, and staff",
      "Magic-users are the PHB's general arcane spellcasters. They are fragile and weak in ordinary combat but gain the broadest arcane spell selection. Spells are learned and recorded in spellbooks, then memorized/prepared before use; casting consumes the prepared use until the character studies again.\n\nIntelligence controls important spell-learning limits. At high level, magic-users can create magical writings and items under the DMG procedures and can eventually establish a stronghold. The class uses d4 hit dice through its normal hit-die progression and then receives fixed hit points per level.");

    add("Illusionist","Magic-User subclass","PHB","INT 15 minimum; DEX 16 minimum; no PHB high-ability XP bonus","d4","Any","No armor or shield; restricted magic-user-style weapon selection",
      "Illusionists are specialized arcane casters with their own spell list. They follow the magic-user spellbook and memorization model but focus on illusion-related magic. The PHB does not give them the normal high-ability experience bonus despite their demanding Intelligence and Dexterity requirements.\n\nTheir usable magic-item list is narrower than a normal magic-user's, although it includes compatible scrolls, all rings, selected rods/staves/wands, certain robes and books, and magic daggers. At 10th level they can begin creating magical items that produce or sustain illusion.");

    add("Thief","Thief","PHB","DEX 9 minimum; Dexterity is the major ability; DEX 16+ gives 10% XP bonus","d6","Neutral or evil; neutral good is possible","Light/leather armor; thief weapon list; no normal shield while performing thief functions",
      "Thieves specialize in pick pockets, open locks, find/remove traps, move silently, hide in shadows, hear noise, climb walls, and back stabbing. Their percentage abilities improve by level and can be modified by race and Dexterity.\n\nBack stabbing from behind gains a substantial attack bonus and multiplies weapon damage, with the multiplier increasing by level. Thieves know Thieves' Cant, begin gaining read-languages capability at 4th level, and at 10th can attempt to use many non-clerical scrolls with a risk of misreading. A high-level thief can establish a headquarters and attract a gang.");

    add("Assassin","Thief subclass","PHB","STR 12, INT 11, DEX 12 minimum; no high-ability XP bonus","d6","Evil only","Broad weapon access; thief-derived equipment limits still apply when performing thief functions",
      "Assassins combine thief abilities with poison use, disguise, spying, back stabbing, and the special assassination procedure. Most thief skills are performed as a thief two levels lower, while assassination and poison use provide a distinct approach to surprised or unaware targets.\n\nDisguise can represent different social roles, classes, races, and sexes but always carries a chance of detection. Upper-rank assassin advancement is tied to the limited guild hierarchy, and reaching the highest ranks may require defeating the current holder.");

    add("Monk","Monk","PHB","STR 15, WIS 15, DEX 15, CON 11 minimum; no XP bonus","2d4 at 1st, then d4 progression","Lawful only","No armor or shield; limited monk weapons plus open-hand combat",
      "Monks are lawful martial specialists with a unique unarmed-combat progression, thief-like skills, unusual saving throws, and many level-based powers. Strength bonuses do not improve monk attack or damage, and the class does not use ordinary armor.\n\nAs level rises, open-hand damage and attack frequency increase; stunning and later lethal open-hand effects become possible. Monks gain several thief abilities at their monk level and progressively acquire abilities such as animal speech, mental masking, disease resistance, self-healing, plant speech, charm resistance, poison immunity, and quivering palm. Advancement into the highest ranks is limited and can require single combat with an incumbent monk.");

    add("Bard","Special / appendix class","PHB Appendix II","Human or half-elf; STR 15, WIS 15, DEX 15, CHA 15, INT 12, CON 10; special Fighter→Thief→Bard progression","d6 bard dice added after earlier-class hit dice","Must retain a neutral component","Leather or magical chainmail; no shield; bard weapon list including permitted swords",
      "The PHB Bard is an optional Appendix II class and explicitly depends on DM approval. The character begins as a fighter, changes to thief after the required fighter advancement, then enters bardic study under druids. Earlier fighter/thief hit dice and capabilities are retained under the bard rules.\n\nBards gain druidic spellcasting, automatic languages, musical charm, morale/attack inspiration, legend lore, and magic-item knowledge. They fight at their former fighter level and retain thief functions at their former thief level. A stringed instrument is required, and the PHB bard progression ends at 23rd level.");

    add("Cloistered Cleric","Cleric subclass","Supplied UA variant","Wisdom is the prime requisite; the variant class summary gives no separate minimum score","d6","Any, with lawful tendencies","No armor or shield; club, dagger, horseman's flail, throwing hammer, horseman's mace, quarterstaff",
      "This class is from the supplied UA variant file, whose mechanics are not a clean original-1985 UA presentation. Cloistered clerics are scholarly, lightly equipped priests. They cast cleric spells and turn undead but replace the normal armored-warrior model with religious/healing training, Decipher Script, and Lore.\n\nDecipher Script can interpret unfamiliar, archaic, or coded writing, with a severe penalty for magical scripts. Lore can recall or research notable people, places, legends, languages, and general magic-item purposes; the variant gives a 5% per class level chance to identify an item's general function. Multiclassing with fighter/fighter subclasses is specifically prohibited in this source, though dual-classing into them is allowed.");

    add("Anti-Paladin","Fighter subclass","Supplied UA variant","Charisma is the prime requisite","d10","Chaotic evil only","Any armor, shield, and weapon",
      "The supplied-UA-variant Anti-Paladin is a chaotic-evil fighter subclass. It gains disease immunity, a reversed lay-on-hands effect, fighter-style multiple attacks, poison expertise, sneak attack, an unholy aura, cause disease, command undead, a special mount, and limited divine spellcasting.\n\nLay on hands heals the anti-paladin or undead but harms ordinary living creatures. Sneak attack improves the first attack against an unaware or surprised anatomical target and doubles its damage. Divine casting begins at 8th level from the cleric list. These later/conversion-style mechanics remain clearly separated from verified PHB rules.");

    add("Duelist","Fighter subclass","Supplied UA variant","Dexterity is the prime requisite","d10","Any, with non-lawful tendencies","Light armor and small shields; any weapon",
      "The supplied-UA-variant Duelist is a lightly armored one-on-one combat specialist. Abilities include combat sense, faster movement while lightly equipped, improved parry, fighter-style multiple attacks, signature weapons, weapon finesse, and limited identification of signature-weapon magic.\n\nCombat sense progressively reduces vulnerability to sneak attacks. Parry receives a substantial bonus. A signature weapon gains an attack-or-damage bonus and an accelerated multiple-attack progression; later signature selections improve earlier bonuses. Weapon finesse can substitute Dexterity for Strength on relevant attack, damage, and disarm checks.");

    add("Necromancer","Magic-User subclass","Supplied UA variant","Intelligence is the prime requisite","d4","Any non-good","No armor while casting; club, dagger, dart, quarterstaff, sickle, scythe",
      "The supplied-UA-variant Necromancer is a specialized arcane caster with its own spell list and spellbook. It prepares spells through study like a magic-user but can only record and cast spells on its class list. It begins with embalming and anatomy training.\n\nAt 1st level it gains a bonus against enchantment/charm effects, improving at levels 5, 10, 15, and 20 to a maximum +5. At 3rd level it gains a command-undead ability that advances as a lower-level evil cleric. This entry remains marked variant because the source uses later/conversion-style progression and terminology.");

    add("Psionicist","Primary class","Supplied UA variant","Charisma is the prime requisite; CHA 9 minimum to use powers, with higher CHA required for higher power levels","d6","Any non-chaotic","No armor while using psionics; broadsword, club, dagger, dart, throwing hammer, longsword, quarterstaff, scimitar, short sword, spear",
      "The supplied-UA-variant Psionicist is a dedicated mental-power class. Instead of spell slots, it knows a limited selection of powers and spends power points to activate them spontaneously, provided the character has enough points and sufficient Charisma for the power level.\n\nThe class separately learns psionic attack modes such as Mind Thrust, Ego Whip, Id Insinuation, Psionic Blast, and Psychic Crush, plus defense modes including Thought Shield, Mental Barrier, Intellect Fortress, Tower of Iron Will, and Mind Blank. Armor prevents use of psionic powers and combat modes. These power-point and saving-throw conventions are variant material, not the PHB's original psionics system.");
  }

  static void add(String n,String f,String s,String r,String h,String a,String aw,String d){ ALL.add(new Entry(n,f,s,r,h,a,aw,d)); }
  public static ArrayList<Entry> all(){ return new ArrayList<>(ALL); }
  public static Entry find(String name){ if(name==null)return null; for(Entry e:ALL)if(e.name.equalsIgnoreCase(name.trim()))return e; return null; }
  public static Entry findLoose(String stored){ if(stored==null)return null; String s=stored.trim(); Entry exact=find(s); if(exact!=null)return exact; s=s.replaceFirst("\\s+\\d+$","").trim(); return find(s); }
  public static int levelFrom(String stored){ if(stored==null)return 1; java.util.regex.Matcher m=java.util.regex.Pattern.compile("(\\d+)\\s*$").matcher(stored.trim()); if(m.find())try{return Math.max(1,Integer.parseInt(m.group(1)));}catch(Exception ignored){} return 1; }
  public static Entry legacy(String stored){ return new Entry(stored,"Custom / legacy","Custom / campaign","Campaign-defined","Campaign-defined","Campaign-defined","Campaign-defined","This class entry was preserved from an older save or a campaign-specific class. The Companion has no built-in sourcebook mechanics for it; use Custom / Multi-class to edit the stored value."); }
  private ClassData(){}
}
