package com.patricktinkam.firsteditioncompanion;

import java.util.*;

/** Native, paraphrased character-class reference for the PHB and supplied UA variant. */
public final class ClassData {
  public static final class Entry {
    public final String name, family, source, requirements, hitDie, alignment, armorWeapons, details;
    Entry(String name,String family,String source,String requirements,String hitDie,String alignment,String armorWeapons,String details){
      this.name=name;this.family=family;this.source=source;this.requirements=requirements;this.hitDie=hitDie;this.alignment=alignment;this.armorWeapons=armorWeapons;this.details=details;
    }
    public String label(){return name+"  ["+source+"]";}
    public String quick(){return requirements+"  •  Hit Die: "+hitDie+"  •  Alignment: "+alignment;}
    public String fullDetails(){return "Class: "+name+"\nClass family: "+family+"\nSource: "+source+"\n\nRequirements / prime requisite: "+requirements+"\nHit Die: "+hitDie+"\nAlignment: "+alignment+"\nArmor & weapons: "+armorWeapons+"\n\n"+details;}
  }

  private static final ArrayList<Entry> ALL=new ArrayList<>();
  static {
    add("Cleric","Cleric","PHB","WIS 9 minimum; Wisdom is the principal attribute","d8","Any except true neutral","Any armor and shield; non-edged/non-pointed weapons such as club, flail, hammer, mace, and staff",
      "Clerics are armored divine spellcasters and competent melee combatants. They prepare spells through prayer and use holy symbols as a focus. Their spell role emphasizes protection, recovery, support, and a smaller number of offensive or reversed curative effects. Clerics can turn undead; evil clerics can instead command undead under the campaign rules.\n\nA Wisdom score above 15 grants the PHB 10% experience bonus and high Wisdom can also provide bonus spells. Clerics use d8 hit dice through the normal cleric hit-die progression, then gain fixed hit points at higher level. At 8th level a cleric who establishes a suitable place of worship can attract a body of loyal followers; at 9th level the cleric can construct a religious stronghold. Human single-class clerics have unrestricted racial advancement; nonhuman clerics can be limited by race.\n\nMulticlass note: PHB cleric combinations exist for certain nonhuman races. When cleric is combined with fighter-types, the PHB explicitly permits edged weapons for the combination."),

    add("Druid","Cleric subclass","PHB","WIS 12 minimum; CHA 15 minimum; both must exceed 15 for the 10% XP bonus","d8","True neutral","Leather armor and wooden shield; club, dagger, dart, hammer, scimitar, sling, spear, staff",
      "Druids are nature priests and the PHB's true-neutral clerical subclass. They cast their own nature-oriented divine spell list but cannot turn or control undead. Metal armor interferes with druidic magic, so armor is limited to leather with wooden shields. Druids also gain +2 on saves against fire and lightning attacks.\n\nAt 3rd level they gain plant, animal, and pure-water identification plus the ability to pass through natural undergrowth without leaving a normal trail. At 7th level they become immune to charm from woodland-associated creatures and can change form up to three times per day, once each into a reptile, bird, and mammal; changing form also heals a variable portion of prior damage. Druids know a secret druidic language and gain additional nature-creature languages as they advance.\n\nHigh-level advancement is hierarchical rather than unlimited: only nine 12th-level Druids, three Archdruids, and one Great Druid can hold those ranks, so advancement may require defeating an incumbent."),

    add("Fighter","Fighter","PHB","STR 9 minimum; CON 7 minimum; Strength is the principal attribute","d10","Any","Any armor, shield, and weapon",
      "Fighters are the PHB's strongest general weapon combatants. They have the best access to armor and weapons, the d10 hit die, the strongest normal melee progression, and the fighter multiple-attack schedule at higher levels. Strength above 15 grants the PHB 10% experience bonus.\n\nFighters do not cast spells but can use a broad range of magic weapons, armor, shields, potions, protection scrolls, rings, and other combat-oriented items. At 9th level a fighter may establish a freehold; clearing and holding the surrounding territory can attract men-at-arms and generate revenue from inhabitants. Fighter is also the foundation for the paladin and ranger subclasses."),

    add("Paladin","Fighter subclass","PHB","Human; STR 12, INT 9, WIS 13, CON 9, CHA 17 minimum; STR and WIS both >15 for 10% XP bonus","d10","Lawful good only","Any armor, shield, and weapon",
      "Paladins are lawful-good fighter subclasses with both martial ability and divine powers. Their core PHB benefits include detecting evil while concentrating, +2 on all saving throws, immunity to disease, lay on hands once per day for 2 hit points per paladin level, and the ability to cure disease with increasing weekly frequency. They continuously radiate protection from evil in a small radius.\n\nAt 3rd level a paladin affects undead, demons, and devils as a lower-level cleric; at 4th level the paladin can call a special warhorse. A holy sword in the paladin's hands projects a powerful anti-magic circle as described by the PHB. Cleric spellcasting begins at 9th level and progresses to limited 4th-level cleric magic.\n\nThe class carries strict conduct and possession rules: knowingly committing evil permanently ends paladin status, chaotic acts require penance, wealth is tightly limited, 10% of income is tithed, and only a restricted number of magic items may be retained."),

    add("Ranger","Fighter subclass","PHB","STR 13, INT 13, WIS 14, CON 14 minimum; STR, INT, and WIS all >15 for 10% XP bonus","2d8 at 1st, then d8 progression","Any good","Any normal fighter armor/weapons under the subclass rules",
      "Rangers are good-aligned fighter subclasses specializing in woodcraft, scouting, infiltration, and tracking. They begin unusually tough with two d8 hit dice at 1st level and ultimately receive more hit dice than other fighter-types. Against the PHB's listed 'giant class' humanoids, a ranger adds damage equal to ranger level on successful melee hits.\n\nRangers surprise opponents on 1-3 on d6 and are normally surprised only on a 1. Their tracking system works both underground and outdoors, with chances modified by doors, secret routes, elapsed time, weather, and party size. Limited druidic spellcasting begins at 8th level and limited magic-user spellcasting at 9th. At 10th level rangers gain use of certain clairvoyance/ESP/telepathy-type items and attract 2-24 special followers.\n\nA ranger who becomes non-good permanently loses ranger benefits and becomes a fighter under the PHB rule. Before 8th level rangers cannot hire normal retainers, no more than three rangers may normally operate together, and excess treasure beyond what can be carried must be donated to a worthy cause."),

    add("Magic-User","Magic-User","PHB","INT 9 minimum; DEX 6 minimum; Intelligence is the principal attribute; INT 16+ gives 10% XP bonus","d4","Any","No armor or shield; very restricted weapons, chiefly dagger, dart, and staff",
      "Magic-users are the PHB's general arcane spellcasters. They are physically fragile and poor weapon combatants, but gain the broadest arcane spell progression and access to many magic-user-only scrolls, wands, staves, and miscellaneous magical items.\n\nA magic-user learns and records spells in spellbooks, then prepares/memorizes specific spells before use. Casting expends that preparation, requiring renewed study before the spell can be cast again. Intelligence controls important spell-learning and maximum-spell-level limits.\n\nAt 11th level a magic-user can begin enchanting items and scribing magic scrolls under the DMG procedures. At 12th level or higher a magic-user can establish a stronghold and clear/rule surrounding territory. The class uses d4 hit dice through 11th level and then gains fixed hit points per level."),

    add("Illusionist","Magic-User subclass","PHB","INT 15 minimum; DEX 16 minimum; no PHB high-ability XP bonus","d4","Any","No armor or shield; restricted magic-user-style weapon selection",
      "Illusionists are a specialized magic-user subclass with their own spell list emphasizing illusion and related magic. They use d4 hit dice and broadly follow the magic-user model of spellbooks, memorization, fragile defenses, and weak conventional combat.\n\nUnlike normal magic-users, the PHB grants no 10% experience bonus for exceptional Intelligence or Dexterity. Illusionists also have a narrower magic-item list: they can use non-fighter-only potions, illusionist scrolls and compatible magic-user scrolls, all rings, selected rods/staves/wands, certain robes/books/items, and magic daggers.\n\nAt 10th level and above illusionists can manufacture magical items that create or sustain illusion, using procedures broadly comparable to magic-user item creation."),

    add("Thief","Thief","PHB","DEX 9 minimum; Dexterity is the major ability; DEX 16+ gives 10% XP bonus","d6","Neutral or evil; neutral good is possible but uncommon","Light/leather armor; no normal shield for thieving; thief weapon list including club, dagger, dart, sling, and swords allowed by the PHB",
      "Thieves are specialists in stealth, intrusion, traps, climbing, and opportunistic combat. Primary PHB functions are pick pockets, open locks, find/remove traps, move silently, and hide in shadows; secondary abilities include hearing noise, climbing walls, and back stabbing. Success chances increase with level and can be modified by race and Dexterity.\n\nBack stabbing from behind multiplies weapon damage, beginning at double damage for levels 1-4 and increasing by another multiple every four levels, while surprise attacks from behind receive +4 to hit. Thieves know Thieves' Cant. At 4th level they begin acquiring a percentage chance to read languages; at 10th they can attempt to use most non-clerical scrolls, but misunderstanding or reversal is possible.\n\nA 10th-level thief can establish a local headquarters and attract a gang, although doing so risks conflict with the existing thieves' guild."),

    add("Assassin","Thief subclass","PHB","STR 12, INT 11, DEX 12 minimum; no high-ability XP bonus","d6","Evil only","Any weapon and shield; thief-derived restrictions still matter when performing thief functions",
      "Assassins combine thief abilities with professional killing, poison use, disguise, spying, and assassination. They use the thief combat table and back-stab rules, but most thief functions are performed as a thief two levels lower than the assassin's actual level.\n\nOn a surprised victim an assassin may choose the special assassination procedure instead of an ordinary attack; failure still allows normal weapon damage, and poison can impose its own saving throw. Assassins can use poison deliberately, can disguise themselves as different social types, classes, races, or sexes with a detection chance, and at higher levels can learn additional alignment languages if Intelligence is high enough.\n\nAdvancement above the highest ordinary assassin ranks is tied to defeating incumbent guild leaders. Hireling access also expands with level."),

    add("Monk","Monk","PHB","STR 15, WIS 15, DEX 15, CON 11 minimum; no XP bonus","2d4 at 1st, then d4 progression","Lawful only","No armor or shield; limited monk weapon list plus open-hand combat",
      "Monks are lawful martial specialists with unusual unarmed combat, thief-like skills, and progressively supernatural discipline. Strength bonuses do not improve monk attack or damage rolls, and Dexterity does not provide the ordinary armor-class adjustment described for other characters.\n\nMonks gain increasing open-hand damage and multiple attacks, can stun on sufficiently high attack rolls, and at higher level can potentially kill a stunned foe with a specialized open-hand result. They use thief saving throws but can avoid many effects entirely on a successful save; from 9th level, many damaging effects are reduced to half even on a failed save. Monks also gain thief abilities such as open locks, find/remove traps, move silently, hide in shadows, hear noise, and climb walls at their actual monk level.\n\nLevel-based abilities include speaking with animals, mental masking, disease immunity, resistance to haste/slow, feigned death, self-healing, speaking with plants, growing charm resistance, poison immunity, immunity to geas/quest, and eventually quivering palm. High-level advancement is limited by incumbent masters and may require defeating a higher-ranked monk in single unarmed combat."),

    add("Bard","Special / appendix class","PHB Appendix II","Human or half-elf; STR 15, WIS 15, DEX 15, CHA 15, INT 12, CON 10 minimum; special Fighter→Thief→Bard progression","d6 bard dice added after prior-class hit dice","Must retain a neutral component","Leather or magical chainmail; no shield; club, dagger, dart, javelin, sling, scimitar, spear, staff, and permitted swords",
      "The PHB bard is an optional, unusually structured class and is explicitly subject to DM approval. A future bard begins as a fighter, changes to thief after reaching at least 5th fighter level but before 8th, then changes again into bardic/druidic study after gaining sufficient thief experience. Previously earned fighter/thief hit dice are retained.\n\nOnce a bard, the character gains druidic spellcasting, bardic lore, automatic additional languages, musical charm, and item/legend knowledge. The bard continues to fight at the former fighter level and uses thief abilities at the former thief level, while saving throws use the most favorable applicable table with bard level treated as druid level.\n\nBardic poetry can improve allied morale and attack chances after two rounds of performance, music can counter harmful song effects, and the bard's charm chance improves by level. The bard must carry a stringed instrument. The PHB bard progression ends at 23rd level."),

    add("Cloistered Cleric","Cleric subclass","Supplied UA variant","Wisdom is the prime requisite; this variant gives no separate minimum score in the class summary","d6","Any, with lawful tendencies","No armor or shield; club, dagger, horseman's flail, throwing hammer, horseman's mace, quarterstaff",
      "This class comes from the supplied UA variant document, not a clean original 1985 UA rules text. It represents a scholarly/monastic priest rather than the PHB's armored warrior-priest. It casts from the cleric spell list, turns undead, and gains religious/healing training, Decipher Script, and Lore.\n\nDecipher Script uses Intelligence to understand unfamiliar, archaic, or coded writing; arcane or divine scripts can be attempted at a severe penalty for identification purposes but this does not grant unauthorized spellcasting. Lore can recall or research people, places, legends, languages, and the general purpose of magic items, with a 5% per class level chance to identify an item's general function.\n\nThe variant allows rings/cloaks of protection and bracers of defense despite prohibiting armor. Multiclassed or dual-classed cloistered clerics can use equipment permitted by another class, but this source specifically forbids multiclassing with fighter or fighter subclasses while allowing dual-classing into them."),

    add("Anti-Paladin","Fighter subclass","Supplied UA variant","Charisma is the prime requisite","d10","Chaotic evil only","Any armor, shield, and weapon",
      "This supplied-UA-variant class is the chaotic-evil mirror of a paladin. It gains immunity to disease, a reversed style of lay on hands, fighter-style multiple attacks, poison expertise, sneak attack, an unholy aura, cause disease, command undead, a fiendish mount, and limited divine spellcasting.\n\nLay on hands heals the anti-paladin or undead for 2 hit points per class level once per day but damages ordinary living creatures instead. Sneak attack doubles the first successful attack's damage against an unaware or surprised anatomical target and grants a to-hit bonus. The unholy aura improves Armor Class and saves against good creatures and blocks bodily contact from many summoned/conjured foes.\n\nAt 3rd level cause disease and command-undead abilities begin; at 4th level a special mount can be called. Divine spellcasting begins at 8th level, uses the cleric list, and advances to limited 4th-level spells. The source presents this class with later/conversion-style mechanics and should not be confused with verified PHB 1e rules."),

    add("Duelist","Fighter subclass","Supplied UA variant","Dexterity is the prime requisite","d10","Any, with non-lawful tendencies","Light armor and small shields; any weapon",
      "The supplied-UA-variant duelist is a lightly armored specialist in individual combat. Core abilities are combat sense, faster movement in light/no armor, improved parry, fighter-style multiple attacks, signature weapons, Dexterity-based weapon finesse, and limited identification of the magical properties of signature weapons.\n\nCombat sense reduces or eventually eliminates vulnerability to sneak attacks. Improved parry grants +3 on parry attempts. A signature weapon chosen at 1st level gains +1 either to attack or damage and receives the class's accelerated multiple-attack schedule; additional signature weapons are chosen later and prior signature bonuses increase. Weapon finesse lets Dexterity replace Strength for attack/damage and certain disarm checks with signature weapons when lightly equipped.\n\nAt 10th level a duelist can establish a training school and attract paying students. The mechanics in this entry are from the supplied conversion-style UA variant."),

    add("Necromancer","Magic-User subclass","Supplied UA variant","Intelligence is the prime requisite","d4","Any non-good","No armor while casting; club, dagger, dart, quarterstaff, sickle, scythe",
      "This supplied-UA-variant necromancer is a specialized arcane caster with its own necromancy-oriented spell list and spellbook. It prepares spells by study like a magic-user but can only record and cast spells allowed by the necromancer list. The class can use ordinary magic-user items except spell-storing or scroll effects outside its list, with special access to undead-control/protection writings.\n\nThe class begins with embalming and anatomy training. It gains +1 on saves against enchantment/charm effects at 1st level, increasing at 5th, 10th, 15th, and 20th level to +5. At 3rd level it gains command undead as a lower-level evil cleric, improving with level. Starting spellbook size is tied to 1st-level casting capacity plus read magic under the variant.\n\nThis is explicitly treated as supplied-UA-variant material because its spell progression and terminology are not a clean transcription of original 1985 AD&D 1e UA."),

    add("Psionicist","Primary class","Supplied UA variant","Charisma is the prime requisite; CHA 9 minimum to use powers, with higher CHA required for the highest power levels","d6","Any non-chaotic","No armor while using psionics; broadsword, club, dagger, dart, throwing hammer, longsword, quarterstaff, scimitar, short sword, spear",
      "The supplied-UA-variant psionicist is a dedicated mental-power class. Instead of preparing spells, the psionicist knows a limited list of powers and spends a pool of power points to use them. Powers can be used spontaneously as long as enough points remain and the character meets the Charisma requirement for the power level.\n\nThe class learns dedicated psionic attack and defense modes as it advances. Attack modes include Mind Thrust, Ego Whip, Id Insinuation, Psionic Blast, and Psychic Crush; defense modes include Thought Shield, Mental Barrier, Intellect Fortress, Tower of Iron Will, and Mind Blank. Unlike normal powers, these modes do not count against the number of known powers.\n\nThe source gives d6 hit dice, non-chaotic alignment, broad weapon access, and explicitly forbids use of psionic powers or combat modes while armored. This class belongs to the supplied conversion-style UA variant and uses later saving-throw/power-point conventions rather than verified PHB 1e psionics." );
  }

  static void add(String n,String f,String s,String r,String h,String a,String aw,String d){ALL.add(new Entry(n,f,s,r,h,a,aw,d));}
  public static ArrayList<Entry> all(){return new ArrayList<>(ALL);}
  public static Entry find(String name){if(name==null)return null;for(Entry e:ALL)if(e.name.equalsIgnoreCase(name.trim()))return e;return null;}
  public static Entry findLoose(String stored){if(stored==null)return null;String s=stored.trim();Entry exact=find(s);if(exact!=null)return exact;s=s.replaceFirst("\\s+\\d+$","").trim();return find(s);}
  public static int levelFrom(String stored){if(stored==null)return 1;java.util.regex.Matcher m=java.util.regex.Pattern.compile("(\\d+)\\s*$").matcher(stored.trim());if(m.find())try{return Math.max(1,Integer.parseInt(m.group(1)));}catch(Exception ignored){}return 1;}
  public static Entry legacy(String stored){return new Entry(stored,"Custom / legacy","Custom / campaign","Campaign-defined","Campaign-defined","Campaign-defined","Campaign-defined","This class entry was preserved from an older save or a campaign-specific class. The Companion has no built-in sourcebook mechanics for it; use Custom / Multi-class to edit the stored value.");}
  private ClassData(){}
}
