package com.patricktinkam.firsteditioncompanion;

import android.app.*;
import android.os.Bundle;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;
import java.util.regex.*;

public class MainActivity extends Activity {
  static final int BG=Color.rgb(17,17,15),PANEL=Color.rgb(31,30,26),GOLD=Color.rgb(201,168,91),TXT=Color.rgb(238,232,215),MUT=Color.rgb(180,172,151);
  SharedPreferences p; LinearLayout host; String page="Sheet"; Random rng=new Random(); ArrayList<String> history=new ArrayList<>();
  int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);} int I(String k,int d){return p.getInt(k,d);} String S(String k,String d){return p.getString(k,d);} void si(String k,int v){p.edit().putInt(k,v).apply();} void ss(String k,String v){p.edit().putString(k,v).apply();}
  @Override public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("fec",0);shell();show("Sheet");}
  GradientDrawable bg(int c){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(12));g.setStroke(dp(1),Color.rgb(77,69,51));return g;}
  TextView t(String s,int z,int c,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(dp(6),dp(6),dp(6),dp(6));if(bold)v.setTypeface(null,1);return v;}
  Button b(String s){Button v=new Button(this);v.setText(s);v.setTextColor(TXT);v.setAllCaps(false);v.setBackground(bg(PANEL));return v;}
  EditText e(String s,String hint,boolean num){EditText v=new EditText(this);v.setText(s);v.setHint(hint);v.setTextColor(TXT);v.setHintTextColor(Color.DKGRAY);v.setSingleLine(true);v.setPadding(dp(10),dp(8),dp(10),dp(8));v.setBackground(bg(Color.rgb(42,40,34)));if(num)v.setInputType(4098);return v;}
  LinearLayout card(String title){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(12),dp(10),dp(12),dp(10));x.setBackground(bg(PANEL));x.addView(t(title,18,GOLD,true));return x;}
  void add(LinearLayout col,View v){LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,-2);q.setMargins(dp(7),dp(6),dp(7),dp(6));col.addView(v,q);}
  void shell(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);setContentView(root);TextView title=t("FIRST EDITION COMPANION  •  1e Prototype",18,GOLD,true);title.setGravity(Gravity.CENTER);root.addView(title,new LinearLayout.LayoutParams(-1,dp(52)));float w=getResources().getDisplayMetrics().widthPixels/getResources().getDisplayMetrics().density;boolean wide=w>=700;LinearLayout body=new LinearLayout(this);body.setOrientation(wide?0:1);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=new LinearLayout(this);nav.setOrientation(wide?1:0);String[] tabs={"Sheet","Combat","Spells","Gear","Dice","Notes"};for(String x:tabs){Button z=b(x);z.setOnClickListener(v->show(x));nav.addView(z,wide?new LinearLayout.LayoutParams(-1,dp(50)):new LinearLayout.LayoutParams(dp(100),dp(48)));}if(wide)body.addView(nav,new LinearLayout.LayoutParams(dp(155),-1));else{HorizontalScrollView h=new HorizontalScrollView(this);h.addView(nav);body.addView(h,new LinearLayout.LayoutParams(-1,-2));}host=new LinearLayout(this);body.addView(host,new LinearLayout.LayoutParams(wide?0:-1,wide?-1:0,1));}
  LinearLayout col(){LinearLayout c=new LinearLayout(this);c.setOrientation(1);c.setPadding(dp(6),dp(6),dp(6),dp(22));return c;}
  void show(String x){page=x;host.removeAllViews();ScrollView s=new ScrollView(this);LinearLayout c=col();s.addView(c);host.addView(s,new LinearLayout.LayoutParams(-1,-1));if(x.equals("Combat"))combat(c);else if(x.equals("Spells"))spells(c);else if(x.equals("Gear"))gear(c);else if(x.equals("Dice"))dice(c);else if(x.equals("Notes"))notes(c);else sheet(c);}
  abstract class W implements TextWatcher{public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){}}
  void field(LinearLayout c,String label,String key,String def,boolean num){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.addView(t(label,14,MUT,true),new LinearLayout.LayoutParams(dp(125),-2));EditText q=e(num?String.valueOf(I(key,Integer.parseInt(def))):S(key,def),label,num);q.addTextChangedListener(new W(){public void afterTextChanged(Editable z){if(num){try{si(key,Integer.parseInt(z.toString()));}catch(Exception ex){}}else ss(key,z.toString());}});r.addView(q,new LinearLayout.LayoutParams(0,-2,1));c.addView(r);}
  void sheet(LinearLayout c){LinearLayout a=card("Character");field(a,"Name","name","New Character",false);field(a,"Race","race","Human",false);field(a,"Alignment","alignment","",false);field(a,"Class(es)","classes","Fighter 1",false);field(a,"Experience","xp","0",false);add(c,a);LinearLayout v=card("Core Numbers");field(v,"Current HP","hp","8",true);field(v,"Max HP","hpmax","8",true);field(v,"Armor Class","ac","10",true);field(v,"THAC0","thac0","20",true);add(c,v);LinearLayout ab=card("Ability Scores");for(String k:new String[]{"STR","INT","WIS","DEX","CON","CHA"})field(ab,k,k,"10",true);add(c,ab);LinearLayout sv=card("Saving Throws");String[][] saves={{"Poison / Death","save1"},{"Petrify / Poly","save2"},{"Rod / Staff / Wand","save3"},{"Breath Weapon","save4"},{"Spell","save5"}};for(String[] q:saves)field(sv,q[0],q[1],"20",true);add(c,sv);}
  void combat(LinearLayout c){LinearLayout hp=card("Combat Dashboard");TextView h=t("HP  "+I("hp",8)+" / "+I("hpmax",8)+"     AC  "+I("ac",10)+"     THAC0  "+I("thac0",20),24,GOLD,true);h.setGravity(Gravity.CENTER);hp.addView(h);LinearLayout row=new LinearLayout(this);for(int n:new int[]{-5,-1,1,5}){Button q=b((n>0?"+":"")+n+" HP");q.setOnClickListener(v->{si("hp",Math.min(I("hpmax",8),I("hp",8)+n));show("Combat");});row.addView(q,new LinearLayout.LayoutParams(0,dp(46),1));}hp.addView(row);add(c,hp);LinearLayout hit=card("THAC0 Attack");EditText ac=e("0","Target AC",true),mod=e(S("atkmod","0"),"Attack modifier",true);hit.addView(t("Target AC",13,MUT,true));hit.addView(ac);hit.addView(t("Attack modifier",13,MUT,true));hit.addView(mod);Button roll=b("Roll Attack");roll.setOnClickListener(v->{try{int target=Integer.parseInt(ac.getText().toString()),m=Integer.parseInt(mod.getText().toString());ss("atkmod",mod.getText().toString());int d=1+rng.nextInt(20),need=I("thac0",20)-target-m;dialog("Attack Roll","d20: "+d+"\nNeed: "+need+"+ vs AC "+target+"\n"+(d>=need?"HIT":"MISS"));}catch(Exception ex){toast("Check target AC/modifier");}});hit.addView(roll);add(c,hit);LinearLayout w=card("Weapon / Damage");field(w,"Weapon","weapon","Long Sword",false);field(w,"Damage","damage","1d8",false);Button dmg=b("Roll Damage");dmg.setOnClickListener(v->{try{String ex=S("damage","1d8");dialog(S("weapon","Weapon")+" Damage",ex+" = "+roll(ex));}catch(Exception z){toast("Use dice like 1d8+2");}});w.addView(dmg);add(c,w);LinearLayout sv=card("Quick Saving Throw Rolls");String[][] saves={{"Poison / Death","save1"},{"Petrify / Poly","save2"},{"Rod / Staff / Wand","save3"},{"Breath Weapon","save4"},{"Spell","save5"}};for(String[] q:saves){Button z=b(q[0]+"  •  "+I(q[1],20)+"+");z.setOnClickListener(v->{int d=1+rng.nextInt(20),n=I(q[1],20);dialog(q[0],"d20: "+d+"\nNeed: "+n+"+\n"+(d>=n?"SUCCESS":"FAILURE"));});sv.addView(z);}add(c,sv);}
  JSONArray tracks(){try{return new JSONArray(S("tracks","[]"));}catch(Exception e){return new JSONArray();}}void save(JSONArray a){ss("tracks",a.toString());}
  void spells(LinearLayout c){c.addView(t("Separate casting tracks keep Cleric, Magic-User, Druid, Illusionist, or house-ruled multiclass spell use independent.",14,MUT,false));JSONArray a=tracks();for(int i=0;i<a.length();i++){JSONObject tr=a.optJSONObject(i);if(tr==null)continue;final int ti=i;LinearLayout k=card(tr.optString("class","Caster")+" • class level "+tr.optInt("level",1));JSONArray sp=tr.optJSONArray("spells");if(sp==null)sp=new JSONArray();for(int j=0;j<sp.length();j++){JSONObject o=sp.optJSONObject(j);if(o==null)continue;final int sj=j;boolean used=o.optBoolean("used");LinearLayout r=new LinearLayout(this);TextView n=t("L"+o.optInt("level",1)+"  "+o.optString("name","Spell")+(used?"  [USED]":""),15,used?MUT:TXT,!used);r.addView(n,new LinearLayout.LayoutParams(0,-2,1));Button u=b(used?"Restore":"Use");u.setOnClickListener(v->{try{o.put("used",!o.optBoolean("used"));save(a);show("Spells");}catch(Exception e){}});r.addView(u);Button d=b("×");d.setOnClickListener(v->{tr.optJSONArray("spells").remove(sj);save(a);show("Spells");});r.addView(d);k.addView(r);}LinearLayout acts=new LinearLayout(this);Button add=b("+ Prepare");add.setOnClickListener(v->spellDialog(a,ti));acts.addView(add,new LinearLayout.LayoutParams(0,dp(48),1));Button rest=b("Rest / Restore All");rest.setOnClickListener(v->{JSONArray q=tr.optJSONArray("spells");for(int j=0;j<q.length();j++)try{q.getJSONObject(j).put("used",false);}catch(Exception e){}save(a);show("Spells");});acts.addView(rest,new LinearLayout.LayoutParams(0,dp(48),1));k.addView(acts);Button del=b("Remove casting track");del.setOnClickListener(v->{a.remove(ti);save(a);show("Spells");});k.addView(del);add(c,k);}Button addTrack=b("+ Add Casting Track");addTrack.setOnClickListener(v->trackDialog());add(c,addTrack);}
  void trackDialog(){LinearLayout x=card("New Track");EditText cl=e("Magic-User","Class",false),lv=e("1","Class level",true);x.addView(cl);x.addView(lv);new AlertDialog.Builder(this).setTitle("Add Casting Track").setView(x).setPositiveButton("Add",(d,w)->{try{JSONArray a=tracks();JSONObject o=new JSONObject();o.put("class",cl.getText().toString());o.put("level",Integer.parseInt(lv.getText().toString()));o.put("spells",new JSONArray());a.put(o);save(a);show("Spells");}catch(Exception z){}}).setNegativeButton("Cancel",null).show();}
  void spellDialog(JSONArray a,int ti){LinearLayout x=card("Prepare Spell");EditText n=e("","Spell name",false),lv=e("1","Spell level",true),copies=e("1","Copies",true);x.addView(n);x.addView(lv);x.addView(copies);new AlertDialog.Builder(this).setTitle("Prepare / Memorize").setView(x).setPositiveButton("Add",(d,w)->{try{JSONArray sp=a.getJSONObject(ti).getJSONArray("spells");int level=Math.max(1,Math.min(9,Integer.parseInt(lv.getText().toString()))),cp=Math.max(1,Math.min(20,Integer.parseInt(copies.getText().toString())));for(int i=0;i<cp;i++){JSONObject o=new JSONObject();o.put("name",n.getText().toString());o.put("level",level);o.put("used",false);sp.put(o);}save(a);show("Spells");}catch(Exception z){}}).setNegativeButton("Cancel",null).show();}
  EditText multi(String key,String hint){EditText q=e(S(key,""),hint,false);q.setSingleLine(false);q.setGravity(Gravity.TOP);q.setInputType(131073);q.addTextChangedListener(new W(){public void afterTextChanged(Editable z){ss(key,z.toString());}});return q;}
  void gear(LinearLayout c){LinearLayout a=card("Equipment, Treasure & Encumbrance");a.addView(multi("gear","Armor, equipment, coins, magic-item charges, encumbrance..."),new LinearLayout.LayoutParams(-1,dp(300)));add(c,a);LinearLayout b=card("Proficiencies & Languages");b.addView(multi("prof","Weapon/nonweapon proficiencies, languages, class abilities..."),new LinearLayout.LayoutParams(-1,dp(220)));add(c,b);}
  void dice(LinearLayout c){LinearLayout a=card("Dice Roller");a.addView(t("Expressions: 1d20+3, 2d8-1, 3d6",13,MUT,false));EditText ex=e("1d20","Dice expression",false);a.addView(ex);TextView out=t("—",44,GOLD,true);out.setGravity(Gravity.CENTER);a.addView(out);Button r=b("ROLL");r.setOnClickListener(v->{try{int n=roll(ex.getText().toString());out.setText(String.valueOf(n));history.add(0,ex.getText()+" = "+n);}catch(Exception z){toast("Use NdM, NdM+K or NdM-K");}});a.addView(r);LinearLayout q=new LinearLayout(this);for(int d:new int[]{4,6,8,10,12,20,100}){Button z=b("d"+d);z.setOnClickListener(v->{int n=1+rng.nextInt(d);out.setText(String.valueOf(n));history.add(0,"d"+d+" = "+n);});q.addView(z,new LinearLayout.LayoutParams(0,dp(46),1));}a.addView(q);add(c,a);LinearLayout h=card("This Session");for(int i=0;i<Math.min(15,history.size());i++)h.addView(t(history.get(i),14,TXT,false));add(c,h);}
  int roll(String s){Matcher m=Pattern.compile("(?i)^\\s*(\\d*)d(\\d+)(?:\\s*([+-])\\s*(\\d+))?\\s*$").matcher(s);if(!m.matches())throw new RuntimeException();int n=m.group(1).isEmpty()?1:Integer.parseInt(m.group(1)),d=Integer.parseInt(m.group(2)),v=0;for(int i=0;i<n;i++)v+=1+rng.nextInt(d);if(m.group(3)!=null)v+=(m.group(3).equals("-")?-1:1)*Integer.parseInt(m.group(4));return v;}
  void notes(LinearLayout c){LinearLayout a=card("Notes / House Rules / Henchmen");a.addView(multi("notes","Session notes, spell notes, followers, class abilities, DM rulings..."),new LinearLayout.LayoutParams(-1,dp(520)));add(c,a);Button backup=b("Copy Character Backup to Clipboard");backup.setOnClickListener(v->{JSONObject o=new JSONObject();try{for(String k:new String[]{"name","race","alignment","classes","xp","weapon","damage","gear","prof","notes","tracks"})o.put(k,S(k,""));for(String k:new String[]{"hp","hpmax","ac","thac0","STR","INT","WIS","DEX","CON","CHA","save1","save2","save3","save4","save5"})o.put(k,I(k,0));}catch(Exception e){}((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("FEC backup",o.toString()));toast("Backup copied");});add(c,backup);}
  void dialog(String a,String m){history.add(0,a+": "+m.replace("\n"," • "));new AlertDialog.Builder(this).setTitle(a).setMessage(m).setPositiveButton("OK",null).show();}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
