package com.patricktinkam.firsteditioncompanion;

import android.app.*;
import android.content.*;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;

public class MainActivityV2 extends MainActivity {
  static final String[] PROFILE_STR={"name","race","alignment","classes","xp","weapon","damage","gear","prof","notes","tracks","atkmod"};
  static final String[] PROFILE_INT={"hp","hpmax","ac","thac0","STR","INT","WIS","DEX","CON","CHA","save1","save2","save3","save4","save5"};

  JSONObject snapshot(){JSONObject o=new JSONObject();try{for(String k:PROFILE_STR)o.put(k,S(k,""));for(String k:PROFILE_INT)o.put(k,I(k,0));}catch(Exception e){}return o;}
  void applySnapshot(JSONObject o){SharedPreferences.Editor ed=p.edit();for(String k:PROFILE_STR)ed.putString(k,o.optString(k,""));for(String k:PROFILE_INT)ed.putInt(k,o.optInt(k,0));ed.apply();}
  JSONArray savedCharacters(){try{return new JSONArray(S("saved_chars","[]"));}catch(Exception e){return new JSONArray();}}
  void saveCharacters(JSONArray a){ss("saved_chars",a.toString());}

  void saveCharacterDialog(){EditText n=e(S("name","Character"),"Save name",false);new AlertDialog.Builder(this).setTitle("Save Character").setMessage("Save the current sheet, gear, notes, and spell tracks as a named profile.").setView(n).setPositiveButton("Save",(d,w)->{String id=n.getText().toString().trim();if(id.isEmpty())id="Character";JSONArray a=savedCharacters();JSONObject snap=snapshot();try{snap.put("_profile",id);boolean replaced=false;for(int i=0;i<a.length();i++){JSONObject q=a.optJSONObject(i);if(q!=null&&id.equalsIgnoreCase(q.optString("_profile"))){a.put(i,snap);replaced=true;break;}}if(!replaced)a.put(snap);saveCharacters(a);toast("Saved "+id);}catch(Exception ex){toast("Could not save character");}}).setNegativeButton("Cancel",null).show();}
  void loadCharacterDialog(){JSONArray a=savedCharacters();if(a.length()==0){toast("No saved characters yet");return;}String[] labels=new String[a.length()];for(int i=0;i<a.length();i++){JSONObject q=a.optJSONObject(i);labels[i]=(q==null?"Character":q.optString("_profile",q.optString("name","Character")))+"  •  "+(q==null?"":q.optString("classes",""));}new AlertDialog.Builder(this).setTitle("Load Character").setItems(labels,(d,which)->{JSONObject q=a.optJSONObject(which);if(q!=null){applySnapshot(q);show("Sheet");toast("Loaded "+q.optString("_profile",q.optString("name","Character")));}}).setNegativeButton("Cancel",null).show();}
  void deleteCharacterDialog(){JSONArray a=savedCharacters();if(a.length()==0){toast("No saved characters yet");return;}String[] labels=new String[a.length()];for(int i=0;i<a.length();i++){JSONObject q=a.optJSONObject(i);labels[i]=q==null?"Character":q.optString("_profile",q.optString("name","Character"));}new AlertDialog.Builder(this).setTitle("Delete Saved Character").setItems(labels,(d,which)->{String name=labels[which];a.remove(which);saveCharacters(a);toast("Deleted saved profile: "+name);}).setNegativeButton("Cancel",null).show();}
  void newCharacter(){new AlertDialog.Builder(this).setTitle("New Character").setMessage("Clear the current working sheet? Saved profiles will not be deleted.").setPositiveButton("Clear",(d,w)->{SharedPreferences.Editor ed=p.edit();for(String k:PROFILE_STR)ed.remove(k);for(String k:PROFILE_INT)ed.remove(k);ed.apply();history.clear();show("Sheet");}).setNegativeButton("Cancel",null).show();}

  @Override void sheet(LinearLayout c){LinearLayout profiles=card("Character Profiles");profiles.addView(t("Current working sheet: "+S("name","New Character"),14,MUT,false));LinearLayout r1=new LinearLayout(this);Button sv=b("Save Character");sv.setOnClickListener(v->saveCharacterDialog());r1.addView(sv,new LinearLayout.LayoutParams(0,dp(48),1));Button ld=b("Load Character");ld.setOnClickListener(v->loadCharacterDialog());r1.addView(ld,new LinearLayout.LayoutParams(0,dp(48),1));profiles.addView(r1);LinearLayout r2=new LinearLayout(this);Button nw=b("New Character");nw.setOnClickListener(v->newCharacter());r2.addView(nw,new LinearLayout.LayoutParams(0,dp(48),1));Button del=b("Delete Saved");del.setOnClickListener(v->deleteCharacterDialog());r2.addView(del,new LinearLayout.LayoutParams(0,dp(48),1));profiles.addView(r2);add(c,profiles);super.sheet(c);}

  void preparedSpellDetail(JSONObject o){String src=o.optString("source","Custom / personal entry"),sum=o.optString("summary","No catalog summary stored for this manually entered spell.");dialog(o.optString("name","Spell"),(o.optInt("level",1)==0?"Cantrip":"Level "+o.optInt("level",1))+"\nSource: "+src+"\n\n"+sum);}
  void addCatalogSpell(JSONArray a,int ti,SpellCatalog.Entry en){try{JSONArray sp=a.getJSONObject(ti).getJSONArray("spells");JSONObject o=new JSONObject();o.put("name",en.name);o.put("level",en.level);o.put("used",false);o.put("source",en.source);o.put("summary",en.summary);sp.put(o);save(a);show("Spells");toast("Prepared "+en.name);}catch(Exception z){toast("Could not add spell");}}
  void catalogDetail(JSONArray a,int ti,SpellCatalog.Entry en){new AlertDialog.Builder(this).setTitle(en.name).setMessage((en.level==0?"Cantrip":"Level "+en.level)+" • "+en.caster+"\nSource: "+en.source+"\n\n"+en.summary+"\n\nOfficial PHB/UA wording is not bundled; use the named book for exact text.").setPositiveButton("Prepare 1",(d,w)->addCatalogSpell(a,ti,en)).setNegativeButton("Close",null).show();}
  void catalogDialog(JSONArray a,int ti){JSONObject tr=a.optJSONObject(ti);if(tr==null)return;String raw=tr.optString("class","Caster"),cls=SpellCatalog.normalizeClass(raw);ArrayList<SpellCatalog.Entry> all=SpellCatalog.forClass(raw);if(all.isEmpty()){toast("No built-in catalog for "+raw+" yet");return;}LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(10),dp(6),dp(10),dp(6));box.addView(t("PHB + Unearthed Arcana catalog for "+cls+". Search by name, level (for example L3), or source.",13,MUT,false));EditText search=e("","Search spells",false);box.addView(search);ListView list=new ListView(this);ArrayList<SpellCatalog.Entry> shown=new ArrayList<>();ArrayList<String> labels=new ArrayList<>();ArrayAdapter<String> adapter=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,labels);list.setAdapter(adapter);box.addView(list,new LinearLayout.LayoutParams(-1,dp(500)));Runnable filter=()->{String q=search.getText().toString().trim().toLowerCase(Locale.US);shown.clear();labels.clear();for(SpellCatalog.Entry en:all){String label=en.label();if(q.isEmpty()||label.toLowerCase(Locale.US).contains(q)){shown.add(en);labels.add(label);}}adapter.notifyDataSetChanged();};search.addTextChangedListener(new W(){public void afterTextChanged(Editable z){filter.run();}});filter.run();AlertDialog dlg=new AlertDialog.Builder(this).setTitle(cls+" Spell Catalog").setView(box).setNegativeButton("Close",null).create();list.setOnItemClickListener((parent,view,pos,id)->{if(pos>=0&&pos<shown.size())catalogDetail(a,ti,shown.get(pos));});dlg.show();}

  @Override void spells(LinearLayout c){c.addView(t("Each casting track keeps its own prepared/memorized copies. Browse PHB + Unearthed Arcana spell names for Cleric, Druid, Magic-User, or Illusionist, then tap a spell to view a concise summary or prepare it.",14,MUT,false));JSONArray a=tracks();for(int i=0;i<a.length();i++){JSONObject tr=a.optJSONObject(i);if(tr==null)continue;final int ti=i;LinearLayout k=card(tr.optString("class","Caster")+" • class level "+tr.optInt("level",1));JSONArray sp=tr.optJSONArray("spells");if(sp==null)sp=new JSONArray();for(int j=0;j<sp.length();j++){JSONObject o=sp.optJSONObject(j);if(o==null)continue;final int sj=j;boolean used=o.optBoolean("used");LinearLayout r=new LinearLayout(this);TextView n=t((o.optInt("level",1)==0?"Cantrip":"L"+o.optInt("level",1))+"  "+o.optString("name","Spell")+(used?"  [USED]":""),15,used?MUT:TXT,!used);n.setOnClickListener(v->preparedSpellDetail(o));r.addView(n,new LinearLayout.LayoutParams(0,-2,1));Button u=b(used?"Restore":"Use");u.setOnClickListener(v->{try{o.put("used",!o.optBoolean("used"));save(a);show("Spells");}catch(Exception e){}});r.addView(u);Button d=b("×");d.setOnClickListener(v->{tr.optJSONArray("spells").remove(sj);save(a);show("Spells");});r.addView(d);k.addView(r);}LinearLayout acts=new LinearLayout(this);Button browse=b("Browse Class Spells");browse.setOnClickListener(v->catalogDialog(a,ti));acts.addView(browse,new LinearLayout.LayoutParams(0,dp(48),1));Button custom=b("+ Custom Spell");custom.setOnClickListener(v->spellDialog(a,ti));acts.addView(custom,new LinearLayout.LayoutParams(0,dp(48),1));k.addView(acts);Button rest=b("Rest / Restore All Prepared Spells");rest.setOnClickListener(v->{JSONArray q=tr.optJSONArray("spells");for(int j=0;j<q.length();j++)try{q.getJSONObject(j).put("used",false);}catch(Exception e){}save(a);show("Spells");});k.addView(rest);Button del=b("Remove casting track");del.setOnClickListener(v->{a.remove(ti);save(a);show("Spells");});k.addView(del);add(c,k);}Button addTrack=b("+ Add Casting Track");addTrack.setOnClickListener(v->trackDialog());add(c,addTrack);}
}
